package com.minimarket.pos.reporting.domain;

public enum AuditEventType {
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGIN_RATE_LIMITED,
    PASSWORD_CHANGED,
    LOGOUT_SUCCEEDED,
    CASH_OPENED,
    CASH_CLOSED,
    CASH_SALE,
    MANUAL_INCOME,
    MANUAL_WITHDRAWAL,
    CASH_REFUND,
    INVENTORY_ENTRY,
    INVENTORY_SALE_OUT,
    INVENTORY_ADJUSTMENT_IN,
    INVENTORY_ADJUSTMENT_OUT,
    INVENTORY_DAMAGED,
    INVENTORY_EXPIRED,
    INVENTORY_SALE_REVERSAL,
    SALE_CONFIRMED,
    SALE_VOIDED
}
